version: '3.8'

services:
  server:
    image: tipstash-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tipstash
      - DB_USER=tipstash
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
        - 5434:5432
    environment:
      POSTGRES_USER: tipstash
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tipstash
    volumes:
      - /Users/swamsley/data/tipstash:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
