export const COINBASE_PRODUCT_REPOSITORY = 'COINBASE_PRODUCT_REPOSITORY';
export const DEAL_REPOSITORY = 'DEAL_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const AUTH_GUARD = 'AUTH_GUARD';
